package com.example.nfc.Models;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.nfc.Models.NfcTransaction;

import com.example.nfc.Models.NfcTransactionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig nfcTransactionDaoConfig;

    private final NfcTransactionDao nfcTransactionDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        nfcTransactionDaoConfig = daoConfigMap.get(NfcTransactionDao.class).clone();
        nfcTransactionDaoConfig.initIdentityScope(type);

        nfcTransactionDao = new NfcTransactionDao(nfcTransactionDaoConfig, this);

        registerDao(NfcTransaction.class, nfcTransactionDao);
    }
    
    public void clear() {
        nfcTransactionDaoConfig.clearIdentityScope();
    }

    public NfcTransactionDao getNfcTransactionDao() {
        return nfcTransactionDao;
    }

}
